language: ruby
rvm:
  - 2.0.0
before_script:
  - git config --global user.name "forecho"
  - git config --global user.email "caizhenghai@gmail.com"
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - bundle exec rake setup_github_pages[$REPO_URL]
  - git checkout -- _config.yml
script:
  - bundle exec rake generate
after_script:
  - bundle exec rake deploy
env:
  global:
  - GH_REPO="forecho/blog"
  - secure: cIyOuboceed07q3Q6OA/CxtOjfhg7HNacY8MjxmRtWUYV7E9oBnWTf5XKg04q7xdHIgQP3SvHu8mP065MPbdGAo+6y2I5SevsBmhiY0UZ3PQ1gZRStenoftIXUSAosbAkUjHEVMKRz2W2kWIEUTh3dJMoVOyx9QBiIk4ZZz0GYPO9lrZzYuIyLOHDTYPov21wjra2onueprndo1/MsOtnAbxN05fKlMIzMujJph68ZmUJR45GtlnZmM5hBiP+wSBP+1oVnBYMrN/jyq1bRxdCMX9yDJilBjyXnQIN3WaKQBFSWRyayTC1v+3i7akXfaATZ/m8gcRvGUo9tR3gjSb+H+dgs8LqSg///kjP1kSZSQW+higlyvmPhTSuZih7Dde+58QTmokk8CgmCdis/BWsffootIgJoFw+9JiZ4agbPatw1aLf380vTe1OGDcPWaRHEY9HJqDya5wWEJTI3825GZ1JRCpCgTISCJe4KizALMzyy1GuwUUT8QM1cb+vzipWSgyxGaDri3HBxn+bawcN3j0l4ALKNte9LewUX87W/U5L+xEmwyHyy2+e6IqG6k41fKeae4jr/2O7QwnO3hOhEJUSbSaKiUYk/BBcK08Mh2g+pk8qi72z7HBsCjyEZnUZYNI1ZzlF8vytZ9dAwqjpY34Cz3iQy0qPVVK55857z0=
notifications:
  webhooks:
    - https://jianliao.com/v1/services/webhook/20dc86bf9bb810a0e336b245798c0247ceb96357
  slack: forecho:SQsHQyf5h6ibbGJAr501gff0
