language: ruby
rvm:
  - 2.0.0
before_script:
  - git config --global user.name "forecho"
  - git config --global user.email "caizhenghai@gmail.com"
  - export REPO_URL="https://github.com/$GH_REPO.git"
  - bundle exec rake setup_github_pages[$REPO_URL]
  - git checkout -- _config.yml
script:
  - bundle exec rake generate
after_script:
  - bundle exec rake deploy
env:
  global:
  - GH_REPO="forecho/blog"
  - secure: "puhDNS9ngXQSVNkgCF55tc8dAJ7kii1gwYG7ux9yhWOh5n66OZmVKbB5/i7+N5eXWKCdzEHrp/RZswpwI9vF86gzRHUdZWc5XRKVfAEoAeJ0KFt0KIAih+OhTQYuatuAoWx4scMfTunVDhbtX5IHL9Uibh2bt5NM9D1E2IqimuT72mm/VQkJKJaByqk3Q2O6hhf6jxwlPyrndQhJTNBlnbHq3ozByunRAj6mxxfS60mhiF0atO02a5dIc+B16SNyYmxD7qXH/gYm5CmovvlPO4zSFZs7U50CqRi0oN8i2qgHO34ET69eZVnfjfFEHvkfo9GqTJhQYInxu39zLhg6o0oLMjzGelkkBpi1TkPX1UKw2pSVvdHgmG8de9gSnIJGkWgkVBJHFF3yMKFiPFPjDzKvxeK8JfbO+K7v/k5jZNThx3Q6GBa9GZmXpaYRVBtV1cPGTxQaFnFopKXWxtirrdUbIIe0lm32Mv3YkpfeDvnr9CDXd7XjApKyoMMr4W4VAsEKK+PgMerNc+gC4Uybs8du0TV/sFGMcUv2pBvn0IQiFCAsk7uxcNoMvpABQ9KD64thW99wVDsSCaD2+4lhzFtSK9uGgsPGkXw3zl/XjVBW0k7+mm3X/aimvWblC4iMdwAQNDuJ1Q29DG7fLF3QMQCX/NjE+zVCFaKvNzc9oLY="