language: ruby
rvm:
  - 2.0.0
  - 1.9.3
gemfile:
  - Gemfile.travis
before_script:
  - git config --global user.name "forecho"
  - git config --global user.email "caizhenghai@gmail.com"
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - bundle exec rake setup_github_pages[$REPO_URL]
script:
  - bundle exec rake generate
after_script:
  - bundle exec rake deploy
env:
  global:
  - GH_REPO="forecho/blog"
  - secure: "R3w2jXSuvAGRn2pCIIpMvmRv6ST2k2aJZ7UH7uSC0I7+VZdr099uQTzvgyyw0bvPJ6RNxzillPTAWiSQQOyZL8yHKCOVMZ5fYIsm9cFYcgunrP/RCcA3OIt9ntrfkvSBtR6NKtSJZAAfVxatQJYDciWtCU5D7MfyF/4jyTrrCmo="