branches:
  only:
  - source
language: ruby
rvm:
  - 1.9.3
gemfile:
  - Gemfile.travis
before_script:
  - git config --global user.name "forecho"
  - git config --global user.email "caizhenghai@gmail.com"
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - bundle exec rake setup_github_pages[$REPO_URL]
script:
  - bundle exec rake generate
after_script:
  - bundle exec rake deploy
env:
  global:
  - GH_REPO="your_github_name/your_github_name.github.io"
  - secure: "b2772864962d5019b90749c7e08c5a6ad2534270"