language: ruby
rvm:
  - 2.1
before_script:
  - git config --global user.name "forecho"
  - git config --global user.email "caizhenghai@gmail.com"
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - bundle exec rake setup_github_pages[$REPO_URL]
  - git checkout -- _config.yml
script:
  - bundle exec rake generate
after_script:
  - bundle exec rake deploy
env:
  global:
  - GH_REPO="forecho/blog"
  - secure: GoGcFpHdMIKgYmqXz3OyvWn5QFtyuO7vJ2hxRhibJYWKLEscZxBVniWB+5n3Lg1HL0UgvwbFMYPd3Kzgxubhvn8cp/AVBUTlvN/EOHg++SyynYgOWJ5ms3KKbgY0bc5eNJBgw/RiN9Y7EW2Z5m5H2LRf0POnB2nXRyRrdJv1fe0Bbnl54VUhIfby5i+CzVgCcc+5dPta5h0c6VtbkiRfNy6w3f8FHR1qruY+e1qN2vLtCTSw1zMoxwz4YPIN2mQMTitFBROKY70Uobe+ZJqoNFMiTQRV/2PpQg21PoR2K72zc7ou7h2YiJRSWzLmIfbmVTZbBRFndHRLKFeIQBNv9B0EigxZCbaBhkd29tv8bjOycoQYoqhld74/Y7JN89h+s/8cb2kNojWdBROx5vdGAjqLF42RAHV5+++pc826G8WMOhWkH+n4RbFw0O4nQe/R6DE3kF1au+OLVIPdJFJ+4lp3vgGjrChPc88JEAeprdGBazYOrY+n2JrR+x3rTX146+0iSeQWkQ6iZyMCelGv8g0nS9wnRJuUwayLbdxBObUp9jqMAgZ0GJRGQBcJvKTHoFj+LEsicmRHc43i6Y9WlZuLDcfhSYDXgXrwfqLHEDblouUgSdb91t/5l2tUIx3jgGxNxzBgMlg3ZJuTy+I7IfxBoOd0BbBU7uOZOA3CpE4=
notifications:
  slack: forecho:SQsHQyf5h6ibbGJAr501gff0
